######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 4 23:06:26 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += effe.cpp
